
cc_library(
    name = "common",
    srcs = [
        "common.cpp",
    ],
    hdrs = [
        "common.h",
    ],
    deps = [

    ]
)

cc_binary(
    name = "type_list",
    srcs = [
        "type_list.cpp",
        "type_list.h",
    ],
    deps = [
        ":common",
    ],
)
