cc_binary(
    name = "radix_sort",
    srcs = [
        "radix_sort.cpp",
        "radix_sort.h",
        "test_radix_sort.cpp",
    ],
    deps = [
        "//alg/data",
    ],
)

cc_binary(
    name = "merge_sort",
    srcs = [
        "merge_sort.cpp",
        "merge_sort.h",
        "test_merge_sort.cpp",
    ],
    deps = [
        "//alg/data",
    ],
)

cc_binary(
    name = "quick_sort",
    srcs = [
        "quick_sort.cpp",
        "quick_sort.h",
        "test_quick_sort.cpp",
    ],
    deps = [
        "//alg/data",
        "//alg/common",
    ],
)
