package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "common",
    srcs = [
        "common.cpp",
    ],
    hdrs = [
        "common.h",
    ],
)

cc_library(
    name = "traits",
    srcs = [
        "traits.cpp",
    ],
    hdrs = [
        "traits.h",
    ],
)
