cc_binary(
    name = "abstract_factory",
    srcs = [
        "abstract_factory.cpp",
    ],
)

cc_binary(
    name = "builder",
    srcs = [
        "builder.cpp",
    ],
)

cc_binary(
    name = "factory",
    srcs = [
        "factory.cpp",
    ],
)

cc_binary(
    name = "prototype",
    srcs = [
        "prototype.cpp",
    ],
)

cc_binary(
    name = "singleton",
    srcs = [
        "singleton.cpp",
    ],
    linkopts = [
        "-pthread",
    ],
)

cc_binary(
    name = "adapter",
    srcs = [
        "adapter.cpp",
    ],
)

cc_binary(
    name = "bridge",
    srcs = [
        "bridge.cpp",
        "bridge.hpp",
    ],
    deps = [
        "@boost//:algorithm",
    ],
)

cc_binary(
    name = "composite",
    srcs = [
        "composite.cpp",
    ],
)

cc_binary(
    name = "iterator",
    srcs = [
        "iterator.cpp",
    ],
)

cc_binary(
    name = "iterator2",
    srcs = [
        "iterator2.cpp",
    ],
)

cc_binary(
    name = "decorator",
    srcs = [
        "decorator.cpp",
    ],
)
