package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "data",
    srcs = [
        "array.cpp",
        "heap.cpp",
        "list.cpp",
    ],
    hdrs = [
        "array.h",
        "heap.h",
        "list.h",
    ],
)
